/**
 *  service/settings.js - Used to setup valuable parameters such as host location, database location, API keys etc.
 *
 *  To access a config variable, this file needs to be required like 'config = require('./service.config')
 *  then config.server.host to get the server host.
 *  TODO: attempt to separate config into separate production and development branches
 */
var config = {
    server: {
        host: 'localhost', // local machine
        port: '54321' // port set on my local machine
    },
    database: {
        promise: 'global.Promise', // promises used for async compute, represents potential values
        port: 'mongodb://localhost/itineraryapp' // location of the database on my machine
    },
    auth: {
        secret: 'penguinsrule' // stub value for attempt at json web token integration
    },
    morgan: {
        format: '| METHOD = :method. URL = :url. STATUS = :status. ' +
        'RESPONSE TIME = :response-time ms. DATE+TIME = :date[web].' // console format for API trace
    },
    google: {
        mapsKey: 'AIzaSyD1O213LeJYDURP4UISrgMKH6dnEAPHJnQ' // maps key generated by google api used in places search
    }
};

// Object returns access to all routes when required by other node js files
module.exports = config;