/**
 *  service/settings.js - Used to setup valuable parameters such as host location, database location, API keys etc.
 *
 *  To access a config variable, this file needs to be required like 'config = require('./service.config')
 *  then config.server.host to get the server host.
 *  TODO: attempt to separate config into separate production and development branches
 */
var config = {
    server: {
        host: 'localhost', // local machine
        port: '54321' // port set on my local machine
    },
    database: {
        SALT_WORK_FACTOR: 10,
        promise: 'global.Promise', // promises used for async compute, represents potential values
        port: 'mongodb://localhost/itineraryapp' // location of the database on my machine
    },
    auth: {
        secret: 'penguinsrule' // stub value for attempt at json web token integration
    },
    morgan: {
        format: '| METHOD = :method. URL = :url. STATUS = :status. ' +
        'RESPONSE TIME = :response-time ms. DATE+TIME = :date[web].' // console format for API trace
    },
    google: {
        mapsKey: 'AIzaSyD1O213LeJYDURP4UISrgMKH6dnEAPHJnQ' // maps key generated by google api used in places search
    },
    validation: {
        MINIMUM_PASSWORD_LENGTH: 10,
        MAXIMUM_PASSSWORD_LENGTH: 72,
    },
    http: {
        SUCCESS_RESPONSE_CODE: 200,
        CONFLICT_RESPONSE_CODE: 409,
        BAD_RESPONSE_CODE: 400,
        UNAUTH_RESPONSE_CODE: 401,
        NOTFOUND_RESPONSE_CODE: 404
    },
    responses: {
        TRIP_DELETED_SUCCESS: "Trip was deleted",
        BAD_EMAIL_PASSWORD: 'Please enter a valid email address and password',
        BAD_TRIP_DETAILS: 'Please fill in a trip name and city',
        EMAIL_USED: 'Email already in use. Please choose another',
        LOGIN_SUCCESS: 'Welcome back!',
        SIGNUP_SUCCESS: 'Successfully created your account',
        NOT_FOUND: 'Not found'
    }
};


// Object returns access to all routes when required by other node js files
module.exports = config;